//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRegistration
    {
        public int RegisterId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> CourseId { get; set; }
        public Nullable<int> StudentId { get; set; }
        public string MobileNo { get; set; }
    
        public virtual tblBatch tblBatch { get; set; }
        public virtual tblCourse tblCourse { get; set; }
    }
}
